#pragma once

#include <map>
#include <string>
#include <vector>

#include "panthera_spectrometer_cell/Types.h"

namespace panthera_spectrometer_cell
{

struct PoseConfig
{
  std::string name;
  Vec3 xyz{0.0, 0.0, 0.0};
  Vec3 rpy{0.0, 0.0, 0.0};
};

struct OutletConfig
{
  OutletId id{OutletId::NONE};
  std::string name;
  std::string dischargeSignal;
  std::string pickApproachPose;
  std::string pickPose;
  std::string returnApproachPose;
  std::string returnPose;
};

struct LoopConfig
{
  double tickRateHz{10.0};
  double waitDischargeSoftTimeoutSec{10.0};
  double actionTimeoutSec{90.0};
  double sensorTimeoutSec{5.0};
  double spectrometerStartTimeoutSec{10.0};
  double scanDurationSec{40.0};
  double detectionTimeoutSec{120.0};
  double resetTimeoutSec{30.0};
};

struct MotionConfig
{
  std::string backend{"fixed_cache"};
  std::string fixedStartPoint{"home_near"};
  double motionServerWaitSec{5.0};
  int transientRetryCount{2};
  double transientRetryDelaySec{0.25};
  double cancelWaitSec{2.0};
  double velocityScale{0.10};
  double accelerationScale{0.10};
  double planningTimeSec{5.0};
  int planningAttempts{5};
  double goalPositionTolerance{0.005};
  double goalOrientationTolerance{0.05};
  double goalJointTolerance{0.01};
  double cartesianEefStep{0.005};
  double cartesianJumpThreshold{0.0};
  double cartesianMinFraction{0.95};
  double outletApproachY{-0.350};
  double outletNearY{-0.390};
  double outletHighZ{0.180};
  double outletGripZ{0.140};
  double outletTransferZ{0.400};
  double spectrometerApproachXOffset{-0.140};
  double spectrometerHighZ{0.360};
  double cleanHighZ{0.240};
  double cleanApproachY{0.260};
  double cleanPreZ{0.160};
  double cleanReadyZ{0.160};
  std::vector<double> safeJointPose{0.0, 0.180, 0.180, 0.0, 0.0, 0.0};
  std::vector<double> homeJointPose{0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
  double errorRecoveryDurationSec{10.0};
  double errorRecoveryPathToleranceRad{0.50};
  double errorRecoveryGoalToleranceRad{0.05};
  double errorRecoverySettleToleranceRad{0.03};
  double errorRecoveryTimeoutMarginSec{5.0};
};

struct GripperConfig
{
  bool commandEnabled{true};
  double openPosition{0.045};
  double closePosition{0.002};
  double openDurationSec{1.5};
  double closeDurationSec{1.5};
  double actionServerWaitSec{5.0};
  double commandTimeoutMarginSec{2.0};
  int retryCount{1};
};

struct PositioningConfig
{
  std::string mode{"sensor_optional"};
  double fixedAxisPositionMm{150.0};
};

struct SpectrometerAxisConfig
{
  double laserMinMm{120.0};
  double laserMaxMm{280.0};
  double axisZeroLaserMm{150.0};
  double axisScaleMPerMm{0.001};
  std::string basePoseName{"spectrometer_base"};
  std::string axis{"y"};
  Vec3 placeOffsetXyz{0.0, 0.0, 0.0};
  Vec3 pickOffsetXyz{0.0, 0.0, 0.0};
};

struct CleaningConfig
{
  std::string approachPose{"clean_approach"};
  std::string dumpPose{"clean_dump"};
  int pourWristJointIndex{5};
  int pourDirection{-1};
  double pourAngleRad{3.141592653589793};
  double pourVelocityScale{0.03};
  double pourAccelerationScale{0.03};
  double pourHoldSec{0.4};
  int shakeCount{1};
  double shakeAngleRad{0.174532925199433};
  double shakeHoldSec{0.15};
  bool brushEnabled{false};
  std::string brushPose{"clean_brush"};
  double brushVelocityScale{0.04};
  double brushAccelerationScale{0.04};
  Vec3 brushApproachOffsetXyz{0.0, -0.10, 0.0};
  Vec3 brushUprightRetreatOffsetXyz{0.0, 0.0, 0.15};
  int brushStrokeCount{3};
  Vec3 brushStrokeOffsetXyz{0.0, 0.04, 0.0};
  double brushHoldSec{0.10};
  double brushMotorStopDelaySec{0.0};
  bool motorRs485Enabled{false};
  std::string motorRs485Device{"/dev/ttyS8"};
  int motorRs485Baudrate{9600};
  int motorRs485SlaveId{2};
  int motorRs485DutyPermille{500};
  int motorRs485CommunicationTimeoutDs{100};
  std::string leavePose{"clean_leave"};
};

struct SimulationConfig
{
  bool enabled{true};
  bool autoGenerateDischarge{true};
  double autoDischargeIntervalSec{3.0};
  double fakeDetectionTimeSec{2.0};
  int actionDelayMs{250};
  double randomFailureRate{0.0};
  unsigned int randomSeed{42};
};

struct CollisionObjectConfig
{
  std::string name;
  std::string type{"box"};
  bool enabled{true};
  std::string frameId{"base_link"};
  Vec3 xyz{0.0, 0.0, 0.0};
  Vec3 rpy{0.0, 0.0, 0.0};
  Vec3 sizeXyz{0.05, 0.05, 0.05};
  double radius{0.03};
  double height{0.05};
};

struct WorkcellConfig
{
  LoopConfig loop;
  MotionConfig motion;
  GripperConfig gripper;
  PositioningConfig positioning;
  SpectrometerAxisConfig spectrometerAxis;
  CleaningConfig cleaning;
  SimulationConfig simulation;
  std::map<OutletId, OutletConfig> outlets;
  std::map<std::string, PoseConfig> namedPoses;
  std::vector<CollisionObjectConfig> collisionObjects;

  static WorkcellConfig withDefaults();
  static WorkcellConfig loadFromFile(const std::string & path);

  const OutletConfig * findOutlet(OutletId outlet) const;
  const PoseConfig * findPose(const std::string & name) const;
  ActionResult validate() const;
};

}  // namespace panthera_spectrometer_cell
