#pragma once

#include <atomic>
#include <chrono>
#include <memory>
#include <mutex>
#include <random>

#include <panthera_interfaces/msg/laser_distance.hpp>
#include <panthera_interfaces/srv/get_laser_distance.hpp>
#include <rclcpp/rclcpp.hpp>
#include <std_srvs/srv/trigger.hpp>

#include "panthera_spectrometer_cell/Config.h"
#include "panthera_spectrometer_cell/Types.h"

namespace panthera_spectrometer_cell
{

class Sensors
{
public:
  Sensors(rclcpp::Node::SharedPtr node, WorkcellConfig config);

  ActionResult initialize();
  void updateConfig(const WorkcellConfig & config);
  DischargeResult readDischargeDone();
  MeasurementResult readSpectrometerPosition();
  bool consumeManualResetRequest();
  bool isEmergencyStopActive() const;

private:
  void setupSimulationServices();
  void setupLaserInterfaces();
  void onLaserDistance(const panthera_interfaces::msg::LaserDistance::SharedPtr msg);
  MeasurementResult readLaserOnce(std::chrono::milliseconds timeout);
  OutletId nextAutoGeneratedOutlet();
  bool shouldSimulateFailure();

  rclcpp::Node::SharedPtr node_;
  rclcpp::Logger logger_;
  WorkcellConfig config_;

  std::atomic_bool pending_outlet_1_{false};
  std::atomic_bool pending_outlet_2_{false};
  std::atomic_bool manual_reset_requested_{false};
  std::atomic_bool emergency_stop_active_{false};

  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr simulate_outlet_1_srv_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr simulate_outlet_2_srv_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr request_reset_srv_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr simulate_estop_srv_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr clear_estop_srv_;
  rclcpp::Subscription<panthera_interfaces::msg::LaserDistance>::SharedPtr laser_sub_;
  rclcpp::Client<panthera_interfaces::srv::GetLaserDistance>::SharedPtr laser_read_once_client_;
  rclcpp::CallbackGroup::SharedPtr laser_callback_group_;

  std::mutex laser_mutex_;
  panthera_interfaces::msg::LaserDistance latest_laser_;
  rclcpp::Time latest_laser_received_time_;
  bool has_laser_{false};

  std::chrono::steady_clock::time_point next_auto_discharge_time_;
  OutletId last_auto_outlet_{OutletId::OUTLET_2};

  std::mt19937 rng_;
  std::uniform_real_distribution<double> unit_dist_{0.0, 1.0};
  std::uniform_real_distribution<double> laser_dist_;
};

}  // namespace panthera_spectrometer_cell
