#include "panthera_spectrometer_cell/Sensors.h"

#include <algorithm>
#include <chrono>
#include <future>
#include <sstream>
#include <thread>
#include <utility>

namespace panthera_spectrometer_cell
{

Sensors::Sensors(rclcpp::Node::SharedPtr node, WorkcellConfig config)
: node_(std::move(node)),
  logger_(node_->get_logger().get_child("sensors")),
  config_(std::move(config)),
  rng_(config_.simulation.randomSeed + 23),
  laser_dist_(config_.spectrometerAxis.laserMinMm, config_.spectrometerAxis.laserMaxMm)
{
  next_auto_discharge_time_ = std::chrono::steady_clock::now() +
    std::chrono::milliseconds(static_cast<int>(config_.simulation.autoDischargeIntervalSec * 1000.0));
}

ActionResult Sensors::initialize()
{
  RCLCPP_INFO(
    logger_,
    "initialize sensors, simulation=%s positioning=%s laser_range=[%.1f, %.1f]mm",
    config_.simulation.enabled ? "true" : "false",
    config_.positioning.mode.c_str(),
    config_.spectrometerAxis.laserMinMm,
    config_.spectrometerAxis.laserMaxMm);

  setupSimulationServices();

  setupLaserInterfaces();

  return ActionResult::ok("sensors initialized");
}

void Sensors::setupLaserInterfaces()
{
  if (config_.positioning.mode != "sensor_offset" || laser_sub_) {
    return;
  }

  // Important:
  // The state-machine timer callback can block for several seconds while executing
  // robot actions. With the default callback group, the laser subscriber may be
  // starved even when the executor is MultiThreadedExecutor. Put the laser
  // subscriber into its own reentrant callback group so the latest laser value can
  // continue to update during robot motion.
  laser_callback_group_ =
    node_->create_callback_group(rclcpp::CallbackGroupType::Reentrant);

  rclcpp::SubscriptionOptions laser_options;
  laser_options.callback_group = laser_callback_group_;

  laser_sub_ = node_->create_subscription<panthera_interfaces::msg::LaserDistance>(
    "/sensors/laser/distance",
    rclcpp::SensorDataQoS(),
    [this](panthera_interfaces::msg::LaserDistance::SharedPtr msg) {
      onLaserDistance(msg);
    },
    laser_options);

  laser_read_once_client_ = node_->create_client<panthera_interfaces::srv::GetLaserDistance>(
    "/laser_distance_node/read_once",
    rmw_qos_profile_services_default,
    laser_callback_group_);
}

void Sensors::updateConfig(const WorkcellConfig & config)
{
  config_ = config;
  laser_dist_ = std::uniform_real_distribution<double>(
    config_.spectrometerAxis.laserMinMm,
    config_.spectrometerAxis.laserMaxMm);
  setupLaserInterfaces();
  next_auto_discharge_time_ = std::chrono::steady_clock::now() +
    std::chrono::milliseconds(static_cast<int>(config_.simulation.autoDischargeIntervalSec * 1000.0));
  RCLCPP_WARN(
    logger_,
    "sensor config reloaded positioning=%s laser_range=[%.1f, %.1f]mm",
    config_.positioning.mode.c_str(),
    config_.spectrometerAxis.laserMinMm,
    config_.spectrometerAxis.laserMaxMm);
}

DischargeResult Sensors::readDischargeDone()
{
  if (pending_outlet_1_.exchange(false)) {
    return DischargeResult{true, OutletId::OUTLET_1, "manual outlet 1 discharge done"};
  }

  if (pending_outlet_2_.exchange(false)) {
    return DischargeResult{true, OutletId::OUTLET_2, "manual outlet 2 discharge done"};
  }

  if (config_.simulation.enabled && config_.simulation.autoGenerateDischarge) {
    const auto now = std::chrono::steady_clock::now();
    if (now >= next_auto_discharge_time_) {
      const OutletId outlet = nextAutoGeneratedOutlet();
      next_auto_discharge_time_ = now +
        std::chrono::milliseconds(static_cast<int>(config_.simulation.autoDischargeIntervalSec * 1000.0));
      return DischargeResult{true, outlet, "auto generated discharge signal"};
    }
  }

  // Real RS485/IO discharge signals can be added here. During commissioning the HMI
  // trigger services above are intentionally kept available for controlled stepping.
  return DischargeResult{false, OutletId::NONE, "no discharge signal"};
}

MeasurementResult Sensors::readSpectrometerPosition()
{
  if (config_.positioning.mode == "fixed") {
    return MeasurementResult::ok(
      config_.positioning.fixedAxisPositionMm,
      "fixed nominal spectrometer position");
  }

  if (config_.simulation.enabled) {
    if (shouldSimulateFailure()) {
      return MeasurementResult::fail("readSpectrometerPosition failed: simulated laser failure");
    }

    const double value = laser_dist_(rng_);
    return MeasurementResult::ok(value, "simulated laser measurement");
  }

  // Wait briefly for a fresh laser sample instead of immediately using a stale
  // cache. This works together with the dedicated laser callback group above.
  const double timeout_sec = std::max(0.2, config_.loop.sensorTimeoutSec);
  const auto deadline = std::chrono::steady_clock::now() +
    std::chrono::milliseconds(static_cast<int>(timeout_sec * 1000.0));

  std::string last_error = "readSpectrometerPosition failed: no laser message received";

  while (std::chrono::steady_clock::now() < deadline) {
    {
      std::lock_guard<std::mutex> lock(laser_mutex_);

      if (!has_laser_) {
        last_error = "readSpectrometerPosition failed: no laser message received";
      } else {
        const double age_sec = (node_->now() - latest_laser_received_time_).seconds();

        if (age_sec > config_.loop.sensorTimeoutSec) {
          std::ostringstream out;
          out << "readSpectrometerPosition waiting for fresh laser data: age="
              << age_sec << "s";
          last_error = out.str();
        } else if (!latest_laser_.valid) {
          last_error =
            "readSpectrometerPosition failed: laser invalid: " + latest_laser_.status;
        } else {
          return MeasurementResult::ok(latest_laser_.distance_mm, "real laser measurement");
        }
      }
    }

    std::this_thread::sleep_for(std::chrono::milliseconds(20));
  }

  std::ostringstream out;
  out << "readSpectrometerPosition failed: laser data timeout after waiting "
      << timeout_sec << "s; last_status=" << last_error;

  RCLCPP_WARN(
    logger_,
    "%s; trying /laser_distance_node/read_once fallback",
    out.str().c_str());
  const auto service_result = readLaserOnce(
    std::chrono::milliseconds(static_cast<int>(timeout_sec * 1000.0)));
  if (service_result.success) {
    return service_result;
  }

  return MeasurementResult::fail(out.str() + "; service_fallback=" + service_result.message);
}

bool Sensors::consumeManualResetRequest()
{
  return manual_reset_requested_.exchange(false);
}

bool Sensors::isEmergencyStopActive() const
{
  return emergency_stop_active_.load();
}

void Sensors::onLaserDistance(const panthera_interfaces::msg::LaserDistance::SharedPtr msg)
{
  std::lock_guard<std::mutex> lock(laser_mutex_);
  latest_laser_ = *msg;
  latest_laser_received_time_ = node_->now();
  has_laser_ = true;
}

MeasurementResult Sensors::readLaserOnce(std::chrono::milliseconds timeout)
{
  if (!laser_read_once_client_) {
    return MeasurementResult::fail("read_once laser service client is not initialized");
  }

  const auto wait_step = std::min(timeout, std::chrono::milliseconds(500));
  if (!laser_read_once_client_->wait_for_service(wait_step)) {
    return MeasurementResult::fail("/laser_distance_node/read_once service is not available");
  }

  auto request = std::make_shared<panthera_interfaces::srv::GetLaserDistance::Request>();
  request->slave_id = 1;

  auto future = laser_read_once_client_->async_send_request(request);
  if (future.future.wait_for(timeout) != std::future_status::ready) {
    laser_read_once_client_->remove_pending_request(future);
    return MeasurementResult::fail("/laser_distance_node/read_once service timeout");
  }

  const auto response = future.future.get();
  if (!response->success) {
    return MeasurementResult::fail(
      "/laser_distance_node/read_once failed: " + response->message);
  }

  if (response->distance_mm < config_.spectrometerAxis.laserMinMm ||
      response->distance_mm > config_.spectrometerAxis.laserMaxMm)
  {
    std::ostringstream out;
    out << "/laser_distance_node/read_once distance out of range: "
        << response->distance_mm << "mm";
    return MeasurementResult::fail(out.str());
  }

  {
    std::lock_guard<std::mutex> lock(laser_mutex_);
    latest_laser_.valid = true;
    latest_laser_.distance_mm = response->distance_mm;
    latest_laser_.distance_m = response->distance_m;
    latest_laser_.status = response->message;
    latest_laser_.source = "laser_read_once";
    latest_laser_received_time_ = node_->now();
    has_laser_ = true;
  }

  return MeasurementResult::ok(response->distance_mm, "real laser measurement from read_once");
}

void Sensors::setupSimulationServices()
{
  simulate_outlet_1_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/simulate_outlet_1_done",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      pending_outlet_1_.store(true);
      response->success = true;
      response->message = "queued OUTLET_1 discharge done";
      RCLCPP_INFO(logger_, "%s", response->message.c_str());
    });

  simulate_outlet_2_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/simulate_outlet_2_done",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      pending_outlet_2_.store(true);
      response->success = true;
      response->message = "queued OUTLET_2 discharge done";
      RCLCPP_INFO(logger_, "%s", response->message.c_str());
    });

  request_reset_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/request_reset",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      manual_reset_requested_.store(true);
      response->success = true;
      response->message = "manual reset requested";
      RCLCPP_WARN(logger_, "%s", response->message.c_str());
    });

  simulate_estop_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/simulate_estop",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      emergency_stop_active_.store(true);
      response->success = true;
      response->message = "simulated emergency stop active";
      RCLCPP_ERROR(logger_, "%s", response->message.c_str());
    });

  clear_estop_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/clear_estop",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      emergency_stop_active_.store(false);
      response->success = true;
      response->message = "simulated emergency stop cleared";
      RCLCPP_WARN(logger_, "%s", response->message.c_str());
    });
}

OutletId Sensors::nextAutoGeneratedOutlet()
{
  if (last_auto_outlet_ == OutletId::OUTLET_1) {
    last_auto_outlet_ = OutletId::OUTLET_2;
  } else {
    last_auto_outlet_ = OutletId::OUTLET_1;
  }
  return last_auto_outlet_;
}

bool Sensors::shouldSimulateFailure()
{
  if (!config_.simulation.enabled || config_.simulation.randomFailureRate <= 0.0) {
    return false;
  }
  return unit_dist_(rng_) < config_.simulation.randomFailureRate;
}

}  // namespace panthera_spectrometer_cell
