#include "panthera_spectrometer_cell/Sensors.h"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <sstream>
#include <utility>

namespace panthera_spectrometer_cell
{

Sensors::Sensors(rclcpp::Node::SharedPtr node, WorkcellConfig config)
: node_(std::move(node)),
  logger_(node_->get_logger().get_child("sensors")),
  config_(std::move(config)),
  laser_filter_(config_.spectrometerAxis.laserMinMm, config_.spectrometerAxis.laserMaxMm),
  rng_(config_.simulation.randomSeed + 23),
  laser_dist_(config_.spectrometerAxis.laserMinMm, config_.spectrometerAxis.laserMaxMm)
{
  next_auto_discharge_time_ = std::chrono::steady_clock::now() +
    std::chrono::milliseconds(
    static_cast<int>(config_.simulation.autoDischargeIntervalSec *
    1000.0));
}

ActionResult Sensors::initialize()
{
  RCLCPP_INFO(
    logger_,
    "initialize sensors, simulation=%s positioning=%s laser_range=[%.1f, %.1f]mm",
    config_.simulation.enabled ? "true" : "false",
    config_.positioning.mode.c_str(),
    config_.spectrometerAxis.laserMinMm,
    config_.spectrometerAxis.laserMaxMm);

  setupSimulationServices();

  setupLaserInterfaces();

  return ActionResult::ok("sensors initialized");
}

void Sensors::setupLaserInterfaces()
{
  if ((config_.positioning.mode != "sensor_optional" &&
    config_.positioning.mode != "sensor_offset") || laser_sub_)
  {
    return;
  }

  // Important:
  // The state-machine timer callback can block for several seconds while executing
  // robot actions. With the default callback group, the laser subscriber may be
  // starved even when the executor is MultiThreadedExecutor. Put the laser
  // subscriber into its own reentrant callback group so the latest laser value can
  // continue to update during robot motion.
  laser_callback_group_ =
    node_->create_callback_group(rclcpp::CallbackGroupType::Reentrant);

  rclcpp::SubscriptionOptions laser_options;
  laser_options.callback_group = laser_callback_group_;

  laser_sub_ = node_->create_subscription<panthera_interfaces::msg::LaserDistance>(
    "/sensors/laser/distance",
    rclcpp::SensorDataQoS(),
    [this](panthera_interfaces::msg::LaserDistance::SharedPtr msg) {
      onLaserDistance(msg);
    },
    laser_options);

}

void Sensors::updateConfig(const WorkcellConfig & config)
{
  std::lock_guard<std::mutex> lock(laser_mutex_);
  config_ = config;
  laser_filter_.configure(
    config_.spectrometerAxis.laserMinMm,
    config_.spectrometerAxis.laserMaxMm);
  measurement_capture_after_ = laser_filter_.beginCapture();
  laser_dist_ = std::uniform_real_distribution<double>(
    config_.spectrometerAxis.laserMinMm,
    config_.spectrometerAxis.laserMaxMm);
  setupLaserInterfaces();
  next_auto_discharge_time_ = std::chrono::steady_clock::now() +
    std::chrono::milliseconds(
    static_cast<int>(config_.simulation.autoDischargeIntervalSec *
    1000.0));
  RCLCPP_WARN(
    logger_,
    "sensor config reloaded positioning=%s laser_range=[%.1f, %.1f]mm",
    config_.positioning.mode.c_str(),
    config_.spectrometerAxis.laserMinMm,
    config_.spectrometerAxis.laserMaxMm);
}

DischargeResult Sensors::readDischargeDone()
{
  if (pending_outlet_1_.exchange(false)) {
    return DischargeResult{true, OutletId::OUTLET_1, "manual outlet 1 discharge done"};
  }

  if (pending_outlet_2_.exchange(false)) {
    return DischargeResult{true, OutletId::OUTLET_2, "manual outlet 2 discharge done"};
  }

  if (config_.simulation.enabled && config_.simulation.autoGenerateDischarge) {
    const auto now = std::chrono::steady_clock::now();
    if (now >= next_auto_discharge_time_) {
      const OutletId outlet = nextAutoGeneratedOutlet();
      next_auto_discharge_time_ = now +
        std::chrono::milliseconds(
        static_cast<int>(config_.simulation.autoDischargeIntervalSec *
        1000.0));
      return DischargeResult{true, outlet, "auto generated discharge signal"};
    }
  }

  // Real RS485/IO discharge signals can be added here. During commissioning the HMI
  // trigger services above are intentionally kept available for controlled stepping.
  return DischargeResult{false, OutletId::NONE, "no discharge signal"};
}

MeasurementResult Sensors::readSpectrometerPosition()
{
  if (config_.positioning.mode == "fixed") {
    return MeasurementResult::ok(
      config_.positioning.fixedAxisPositionMm,
      "fixed nominal spectrometer position");
  }

  const bool sensor_optional = config_.positioning.mode == "sensor_optional";

  if (config_.simulation.enabled) {
    if (sensor_optional) {
      return MeasurementResult::ok(
        config_.positioning.fixedAxisPositionMm,
        "simulated optional laser absent; fixed nominal spectrometer position");
    }
    if (shouldSimulateFailure()) {
      return MeasurementResult::fail("readSpectrometerPosition failed: simulated laser failure");
    }

    const double value = laser_dist_(rng_);
    return MeasurementResult::ok(value, "simulated laser measurement");
  }

  if (sensor_optional) {
    std::lock_guard<std::mutex> lock(laser_mutex_);
    if (!has_valid_laser_ever_) {
      std::ostringstream out;
      out << "laser not connected; fixed fallback "
          << config_.positioning.fixedAxisPositionMm << "mm";
      RCLCPP_WARN_THROTTLE(
        logger_, *node_->get_clock(), 10000, "%s", out.str().c_str());
      return MeasurementResult::ok(config_.positioning.fixedAxisPositionMm, out.str());
    }
  }

  {
    std::lock_guard<std::mutex> lock(laser_mutex_);
    const auto sample = laser_filter_.snapshot(
      std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(),
      measurement_capture_after_);
    if (sample.stable) {
      auto result = MeasurementResult::ok(sample.stableMm, "stable filtered laser measurement");
      result.span = sample.spanMm;
      return result;
    }
    if (sample.rawValid) {
      std::ostringstream out;
      out << "waiting for 15 stable laser samples";
      if (sample.filteredValid) {
        out << ": filtered=" << sample.filteredMm << "mm span=" << sample.spanMm << "mm";
      }
      return MeasurementResult::waiting(out.str());
    }
    return MeasurementResult::waiting(
      "waiting for fresh valid laser data in range [120, 280]mm");
  }

  return MeasurementResult::fail("unsupported positioning mode");
}

void Sensors::beginSpectrometerMeasurement()
{
  std::lock_guard<std::mutex> lock(laser_mutex_);
  measurement_capture_after_ = laser_filter_.beginCapture();
}

void Sensors::startScanTracking()
{
  std::lock_guard<std::mutex> lock(laser_mutex_);
  scan_tracker_.start(
    config_.spectrometerAxis.axisZeroLaserMm,
    std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count(),
    laser_filter_.snapshot(
      std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count())
    .sequence,
    config_.loop.scanDurationSec);
}

ScanStatus Sensors::pollScanTracking()
{
  std::lock_guard<std::mutex> lock(laser_mutex_);
  const double now =
    std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();
  const auto laser = laser_filter_.snapshot(now);
  scan_tracker_.update(laser, now);
  return scan_tracker_.status(now);
}

LaserSnapshot Sensors::laserSnapshot() const
{
  std::lock_guard<std::mutex> lock(laser_mutex_);
  const double now =
    std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();
  return laser_filter_.snapshot(now);
}

bool Sensors::consumeManualResetRequest()
{
  return manual_reset_requested_.exchange(false);
}

bool Sensors::isEmergencyStopActive() const
{
  return emergency_stop_active_.load();
}

void Sensors::onLaserDistance(const panthera_interfaces::msg::LaserDistance::SharedPtr msg)
{
  std::lock_guard<std::mutex> lock(laser_mutex_);
  has_valid_laser_ever_ = has_valid_laser_ever_ ||
    (msg->valid && std::isfinite(msg->distance_mm) &&
    msg->distance_mm >= config_.spectrometerAxis.laserMinMm &&
    msg->distance_mm <= config_.spectrometerAxis.laserMaxMm);
  const double now =
    std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();
  laser_filter_.add(msg->distance_mm, msg->valid, now);
  const auto sample = laser_filter_.snapshot(now);
  scan_tracker_.update(sample, now);
}

void Sensors::setupSimulationServices()
{
  simulate_outlet_1_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/simulate_outlet_1_done",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      pending_outlet_1_.store(true);
      response->success = true;
      response->message = "queued OUTLET_1 discharge done";
      RCLCPP_INFO(logger_, "%s", response->message.c_str());
    });

  simulate_outlet_2_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/simulate_outlet_2_done",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      pending_outlet_2_.store(true);
      response->success = true;
      response->message = "queued OUTLET_2 discharge done";
      RCLCPP_INFO(logger_, "%s", response->message.c_str());
    });

  request_reset_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/request_reset",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      manual_reset_requested_.store(true);
      response->success = true;
      response->message = "manual reset requested";
      RCLCPP_WARN(logger_, "%s", response->message.c_str());
    });

  simulate_estop_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/simulate_estop",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      emergency_stop_active_.store(true);
      response->success = true;
      response->message = "simulated emergency stop active";
      RCLCPP_ERROR(logger_, "%s", response->message.c_str());
    });

  clear_estop_srv_ = node_->create_service<std_srvs::srv::Trigger>(
    "/spectrometer_cell/clear_estop",
    [this](
      const std::shared_ptr<std_srvs::srv::Trigger::Request>,
      std::shared_ptr<std_srvs::srv::Trigger::Response> response) {
      emergency_stop_active_.store(false);
      response->success = true;
      response->message = "simulated emergency stop cleared";
      RCLCPP_WARN(logger_, "%s", response->message.c_str());
    });
}

OutletId Sensors::nextAutoGeneratedOutlet()
{
  if (last_auto_outlet_ == OutletId::OUTLET_1) {
    last_auto_outlet_ = OutletId::OUTLET_2;
  } else {
    last_auto_outlet_ = OutletId::OUTLET_1;
  }
  return last_auto_outlet_;
}

bool Sensors::shouldSimulateFailure()
{
  if (!config_.simulation.enabled || config_.simulation.randomFailureRate <= 0.0) {
    return false;
  }
  return unit_dist_(rng_) < config_.simulation.randomFailureRate;
}

}  // namespace panthera_spectrometer_cell
